/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Coupon;

public interface ICoupon {
    public String getName();
    public boolean isValid();
    public int getDiscountPercent();
    public boolean isApplicable(Item item);
    public void doExpire();
}
